export const projects: IProjectData[] = [
    {
        title: "Electroware",
        link: "https://github.com/luc-silva/electroware",
        introduction:"Electroware é um projeto (CRUD) criado com Typescript, React, Express e MongoDB baseado em um marketplace.",
        description: `O projeto possui sistema de contas, carrinhos de compras, lista de desejos, coleções de itens da lista de desejos, criação, compra, edição e busca de produtos. Também é possível avaliar e visualizar o perfil de outros usuários.\nRotas privadas são protegidas por JWT, enquanto as senhas são criptografadas com o bcrypt.`,
        main_project: true,
        images: [
            "project-electroware-1.png",
            "project-electroware-2.png",
            "project-electroware-3.png",
            "project-electroware-4.png",
            "project-electroware-5.png",
        ],
        tags: ["TS", "ReactJS", "MongoDB", "Express", "HTML", "CSS"],
    },
    {
        title: "Bookwise",
        link: "https://github.com/luc-silva/bookwise",
        introduction:"Bookwise é uma aplicação de gerenciamentos de livros.",
        description: `O projeto permite que o usuário possa adicionar livros que leu, ainda vai ler ou deixou de ler em uma conta pessoal. Também permite o upload de imagens e o display de covers dos livros em sua estante, na página inicial.`,
        main_project: true,
        images: [
            "project-bookwise-1.png",
            "project-bookwise-2.png",
            "project-bookwise-3.png",
            "project-bookwise-4.png",
        ],
        tags: ["TS", "ReactJS", "MongoDB", "Express"],
    },
    {
        title: "Weather App",
        link: "https://github.com/luc-silva/weather-app",
        introduction:"Aplicação que exibe a temperaturas de diversas cidades. Configurações são salvas em LocalStorage.",
        description: `Desenvolvida inicialmente com Javascript, hoje remasterizada com ReactJs e Typescript.\n O usuário pode alterar a temperatura da cidade que aparece no display principal bem as demais além de realizar pesquisa à uma cidade em específico.\n O projeto também possui também, além das abas de climas e configurações, a aba de notícias (que mostra 5 notícias fictícias criadas pelo ChatGPT) e a agenda, aba em que o usuário pode criar e salvar tarefas a serem feitas.`,
        main_project: true,
        images: [
            "project-weatherapp-1.png",
            "project-weatherapp-2.png",
            "project-weatherapp-3.png",
            "project-weatherapp-4.png",
        ],
        tags: ["TS", "ReactJS", "HTML", "CSS"],
    },
    {
        title: "Todo Manager",
        introduction:"Aplicação de gerenciamento de tarefas.",
        description: "Desenvolvido inicialmente com JavaScript, o projeto permite que um usuário defina tarefas para sem feitas, podendo especificar datas e prioridades ou até mesmo planejar algum grande feito, também podendo inserir sub-tarefas. \nTambém contém uma dashboard com histórico de tarefas e algumas estatísticas.",
        main_project: true,
        link: "https://github.com/luc-silva/to-do",
        images: [
            "project-todo-1.png",
            "project-todo-2.png",
            "project-todo-3.png",
            "project-todo-4.png",
        ],
        tags: ["TS", "ReactJS", "HTML", "CSS"],
    },
    {
        title: "Restaurant Page",
        link: "https://github.com/luc-silva/restaurant-page",
        introduction:"",
        description: "",
        images: [
            "project-restaurant-1.png",
            "project-restaurant-2.png",
            "project-restaurant-3.png",
            "project-restaurant-4.png",
            "project-restaurant-5.png",
        ],
        tags: ["JS", "ReactJS", "HTML", "CSS"],
    },
    {
        title: "Portfolio",
        link: "https://github.com/luc-silva/portfolio",
        introduction:"",
        description: "",
        images: [
            "project-portfolio-1.png",
            "project-portfolio-2.png",
            "project-portfolio-3.png",
            "project-portfolio-4.png",
            "project-portfolio-5.png",
        ],
        tags: ["TS", "ReactJS", "HTML", "CSS"],
    },
    {
        title: "Etch-A-Sketch",
        link: "https://github.com/luc-silva/Etch-A-Sketch",
        introduction:"",
        description: "",
        images: ["project-etchasketch-1.png", "project-etchasketch-2.png"],
        tags: ["JS", "HTML", "CSS"],
    },
    {
        title: "Calculator",
        link: "https://github.com/luc-silva/calculator",
        introduction:"",
        description: "",
        images: ["project-calculator-1.png"],
        tags: ["JS", "HTML", "CSS"],
    },
];

export const certificates: ICertificate[] = [
    {
        tags: [
            "Javascript",
            "Typescript",
            "HTML & CSS",
            "ReactJS",
            "Node",
            "Git",
            "SQL",
        ],
        certImage: "cert-spreadfullstack.jpg",
        courseName: "Spread Fullstack Developer Bootcamp",
        schoolName: "Digital Innovation One",
        schoolSite: "https://www.dio.me/en",
        additionalInfo: "",
        courseCompletitionDate: "09/06/2022",
        courseLength: 98,
    },
    {
        tags: ["MongoDB", "NoSQL", "NodeJS"],
        certImage: "cert-mongodbnodejspath.png",
        courseName: "MongoDB Node.js Developer Path",
        schoolName: "MongoDB University",
        schoolSite: "https://learn.mongodb.com/",
        additionalInfo: "",
        courseCompletitionDate: "02/17/2022",
        courseLength: 12,
    },
    {
        tags: ["ReactJS", "Dot Net", "SQL"],
        certImage: "cert-intermediatewebdev.jpg",
        courseName: "Desenvolvimento de Sistemas Web Intermediário",
        schoolName: "Recode",
        schoolSite: "https://recode.org.br/",
        additionalInfo:
            "Data de conclusão do curso e emissão do certificado não se condizem**",
        courseCompletitionDate: "31/05/2022",
        courseLength: 40,
    },
    {
        tags: ["Javascript", "HTML & CSS", "Bootstrap", "SQL", "SCRUM"],
        certImage: "cert-basicwebdev.jpg",
        courseName: "Desenvolvimento de Sistemas Web Básico",
        schoolName: "Recode",
        schoolSite: "https://recode.org.br/",
        additionalInfo:
            "Data de conclusão do curso e emissão do certificado não se condizem**",
        courseCompletitionDate: "20/04/2022",
        courseLength: 40,
    },
];

export const tools: ITool[] = [
    {
        name: "Javascript",
        alt: "Javascript logo",
        toolImage: "logo-javascript.png",
        additionalInfo: "",
    },
    {
        name: "Typescript",
        alt: "Typescript logo",
        toolImage: "logo-typescript.png",
        additionalInfo: "",
    },
    {
        name: "ReactJS",
        alt: "ReactJS logo",
        toolImage: "logo-reactjs.png",
        additionalInfo: "",
    },
    {
        name: "NodeJS",
        alt: "NodeJS logo",
        toolImage: "logo-nodejs.png",
        additionalInfo: "",
    },
    {
        name: "Java",
        alt: "Java logo",
        toolImage: "logo-java.png",
        additionalInfo: "",
    },
    {
        name: "Docker",
        alt: "Docker logo",
        toolImage: "logo-docker.png",
        additionalInfo: "",
    },
    {
        name: "Ubuntu",
        alt: "Ubuntu logo",
        toolImage: "logo-ubuntu.png",
        additionalInfo: "",
    },
    {
        name: "MongoDB",
        alt: "MongoDB logo",
        toolImage: "logo-mongo.png",
        additionalInfo: "",
    },
    {
        name: "HTML",
        alt: "HTML logo",
        toolImage: "logo-html.png",
        additionalInfo: "",
    },
    {
        name: "CSS",
        alt: "CSS logo",
        toolImage: "logo-css.png",
        additionalInfo: "",
    },
    {
        name: "SQL",
        alt: "SQL logo",
        toolImage: "logo-sql.png",
        additionalInfo: "Experiência acadêmica.",
    },
    {
        name: "Shell Scripting",
        alt: "Shell logo",
        toolImage: "logo-shell.png",
        additionalInfo: "Experiência acadêmica.",
    },
    {
        name: "Python",
        alt: "Python logo",
        toolImage: "logo-python.png",
        additionalInfo: "Experiência acadêmica.",
    },
];
